# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [65]:
import numpy as np 

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [66]:
arr = np.random.uniform(0, 20, (4,7))
mx = np.max(arr) 
mn = np.min(arr) 
a = 1/(mx-mn) 
b = -a*mn 
nr_arr = a*arr+b 
print(nr_arr)

[[0.00306061 0.36071154 0.89517779 0.79479056 0.0947308  0.10391726
  0.09228557]
 [1.         0.26999776 0.10337306 0.54609362 0.         0.07056339
  0.41649163]
 [0.61475515 0.21537256 0.4253164  0.3421567  0.42493021 0.0517236
  0.30672592]
 [0.13350365 0.00782918 0.79871807 0.29111581 0.71923881 0.13530396
  0.46670777]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
arr = np.random.randint(0, 10, (8, 10))
sum_lines = np.sum(arr , axis = 1)
m = np.where(sum_lines == min(sum_lines))

arr, sum_lines, min(sum_lines), m, arr[m]

(array([[0, 6, 0, 7, 4, 2, 7, 2, 1, 6],
        [0, 3, 9, 0, 2, 6, 1, 7, 2, 0],
        [2, 2, 7, 5, 4, 5, 3, 6, 4, 0],
        [9, 0, 0, 8, 5, 2, 8, 7, 4, 6],
        [7, 2, 0, 5, 8, 1, 5, 9, 5, 3],
        [3, 5, 4, 8, 1, 1, 5, 1, 8, 8],
        [5, 1, 3, 9, 6, 2, 1, 1, 8, 5],
        [9, 3, 8, 3, 0, 2, 1, 3, 0, 8]]),
 array([35, 30, 38, 49, 45, 44, 41, 37]),
 30,
 (array([1], dtype=int64),),
 array([[0, 3, 9, 0, 2, 6, 1, 7, 2, 0]]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
arr1 = np.array([0, 0])
arr2 = np.array([3, 4])
sum((arr1-arr2)**2)**0.5

5.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [6]:
A = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.matrix([[3, -1], [2, 1]])
C = np.matrix([[7, 21], [11, 8], [8, 4]])
x = np.linalg.inv(A)*(-C)*np.linalg.inv(B)
print(x)

[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [24]:
import numpy as np
data = np.loadtxt(r"minutes_n_ingredients.csv", delimiter=",", dtype="int32", skiprows=1)
print(data[0:5, ])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
for i in range(1, data.shape[1]):
    print(data[:, i].min(), data[:, i].max(), data[:, i].mean())

0 2147483647 21601.00169
1 39 9.05528


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [9]:
import pandas as pd
d = pd.DataFrame(data)
d[1].quantile(0.75)

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
zeros = len(np.count_nonzero(data, axis = 1))
data[:, 1] = np.where(data[:, 1] != 0, data[:, 1], 1)
zeros

100000

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
len(np.unique(data[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [12]:
len(np.unique(data[:, 2])), np.unique(data[:, 2])

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
a = data[np.where(data[:, 2] <= 5)]
a

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [14]:
print(np.max(data[:,2]/data[:,1]))
print(data[:, 2]/data[:, 1])

24.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [67]:
x_sorted_desc = data[data[:, 1]. argsort()[::-1]][:100]
x_sorted_desc[:, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [70]:
new_arr = np.random.randint(data.shape[0], size = 10)
data[new_arr, :], new_arr, data.shape[0]

(array([[ 27228,     20,      8],
        [ 92910,     32,      7],
        [350333,     45,     16],
        [168024,     40,     11],
        [105350,     35,     12],
        [291366,      3,      4],
        [455374,      5,      7],
        [123625,     35,      4],
        [122526,     85,      6],
        [243003,     50,     11]]),
 array([84653, 64893, 24869, 18746, 77219, 77188, 77217,  4550, 64299,
        68797]),
 100000)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [36]:
sred = data[:, 2].mean()

suitable_values = len(np.where(data[:, 2] < sred)[0])

print(f'процент рецептов, кол-во ингредиентов в которых меньше среднего: {suitable_values/len(data)*100}%')

процент рецептов, кол-во ингредиентов в которых меньше среднего: 58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [71]:
good_recepts = np.zeros((data.shape[0], 4), dtype=int)
good_recepts[:, :3] = data
good_recepts[np.where(((data[:, 2] <= 5) & (data[:, 1] <= 20))), 3] = 1

good_recepts


array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [47]:
print(len(np.where(good_recepts[:, 3] == 1)[0])/data.shape[0]*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [72]:
short = data[data[:, 1] < 10]
standart = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long = data[data[:, 1] >= 20]

short, standart, long

max_len = min(len(short), len(standart), len(long))

new_data = np.zeros((3, max_len, 3), dtype = int)

new_data[0, :max_len, :] = short[:max_len]
new_data[1, :max_len, :] = short[:max_len]
new_data[2, :max_len, :] = short[:max_len]

(array([[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]]),
 array([[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [ 44120,     17,      5],
        [ 60756,     15,      5],
        [128811,     15,      4]]),
 array([[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [287943,     85,     15],
        [498432,     65,     15],
        [ 81993,    140,     14]]))