In [1]:
import numpy as np

In [5]:
arr = np.array(list(range(10)))
arr, type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [7]:
arr.size

10

In [8]:
arr.shape

(10,)

In [18]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1, arr1.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [21]:
arr2 = arr1.reshape(3, 2)

In [22]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
arr2[0][0] = 10

In [26]:
arr1

array([[10,  2,  3],
       [ 4,  5,  6]])

In [35]:
arr3copy = arr1.copy()
arr3copy, arr1

(array([[10,  2,  3],
        [ 4,  5,  6]]),
 array([[10,  2,  3],
        [ 4,  5,  6]]))

In [38]:
arr1.dtype

dtype('int32')

In [53]:
arr4 = np.array([[3, 6, 7], [5, 0, 43]], 'float32')
arr4, arr4.dtype

(array([[ 3.,  6.,  7.],
        [ 5.,  0., 43.]], dtype=float32),
 dtype('float32'))

In [54]:
arr4.itemsize, arr4.nbytes

(4, 24)

In [56]:
arr5 = np.arange(10).reshape(2, 5)
arr5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
arr6 = np.arange(-1, 1, 0.1, 'float64')
arr6

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [71]:
arr7 = np.linspace(1,15, 30)
arr7

array([ 1.        ,  1.46551724,  1.93103448,  2.39655172,  2.86206897,
        3.32758621,  3.79310345,  4.25862069,  4.72413793,  5.18965517,
        5.65517241,  6.12068966,  6.5862069 ,  7.05172414,  7.51724138,
        7.98275862,  8.44827586,  8.9137931 ,  9.37931034,  9.84482759,
       10.31034483, 10.77586207, 11.24137931, 11.70689655, 12.17241379,
       12.63793103, 13.10344828, 13.56896552, 14.03448276, 14.5       ])

In [76]:
arr8 = np.geomspace(1, 256, num= 9)
arr8

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256.])

In [77]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [80]:
np.zeros((3,3), int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.save('a_ndarr.npy', arr)

TypeError: save() got an unexpected keyword argument 'encoding'

In [88]:
a_ld = np.load('a_ndarr.npy')
a_ld

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr1, arr5

(array([[10,  2,  3],
        [ 4,  5,  6]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [90]:
np.savez('a1_ndarr.npz', first = arr1, second = arr5 )

In [93]:
np_load = np.load('a1_ndarr.npz')
np_load.files

['first', 'second']

In [94]:
np_load['first']

array([[10,  2,  3],
       [ 4,  5,  6]])

In [97]:
np_load['second']

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])